### ISSUE TITLE
Instructions using k3sup, not arkade

### ISSUE THREAD

**Issue by mvniekerk** [alexellis/crud-postgresql-nodejs-openfaas#2]
1. Installing k3sup works as advertised on how-to
2. When trying to install postgres, k3sup says I should use arkade

**Comment by alexellis** [comment]
Hi that's as expected. Did you get what you needed by using arkade?

Alex

**Comment by mvniekerk** [comment]
Got it working thanks. Just placed this here for the next traveller to see.
